Question 2: Print prime number between 1 to 1000

In [ ]:
for num in range(1,1000):
 if num > 1:
     for i in range(2,num):
        if (num % i) == 0:
            break
     else:
           print(num)

Question 1 : Use IF else to for report card

In [ ]:
mark = int(input("Enter your mark:"))
if mark > 90 :
   print("Your Grade is : A+")
elif mark > 85 :
  print ("Your Grade is : A")
elif mark > 75 :
  print ("Your Grade is : B+")
elif mark > 60 :
   print ("Your Grade is : B")
elif mark > 45 :
  print("Your Grade is :  C")
else :
   print(" FAIL . \n You need to try a bit harder")

Enter your mark:55
Your Grade is :  C

Question 3: Use Nested loop to print 1 to 10 tables

In [ ]:
for item in range(1,11):
  print(item)
  for num in range(1,11):
   print(item,"X",num ,"=",item * num )
print("The Tables are over")

Question 4: Use while loop to print X prime number

In [35]:
max = int(input("Enter the maximum limit"))
num = int(input("Enter the prime numbers to be print"))

number = 2
lst = []
while (number <= max):
   i = 2
   count = 0
   while(i <= number//2):
      if(number % i ==0 ):
         count = count + 1
         break
      i= i+1
   if(count == 0):
       lst.append(number)
   number = number + 1
   if len(lst) == num :
      break 
print ("The First ", num ,"is",lst)

Enter the maximum limit 100
Enter the prime numbers to be print 10
The First  10 is [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]